shards: 1
replicaCount: 1

auth:
  username: default
  password: "ClickHouse123!"

persistence:
  enabled: true
  storageClass: gp3
  accessModes:
    - ReadWriteOnce
  size: 8Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

service:
  type: ClusterIP

zookeeper:
  enabled: false