{{- if .Values.eventService.enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: event-service
  labels:
    app: event-service

spec:
  replicas: {{ .Values.eventService.replicas }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: event-service

  template:
    metadata:
      labels:
        app: event-service

    spec:
      containers:
        - name: event-service

          image: "{{ .Values.eventService.image.repository }}:{{ .Values.eventService.image.tag }}"

          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.eventService.port }}
              protocol: TCP
          env:
            - name: CLICKHOUSE_HOST
              value: "clickhouse.clickhouse.svc.cluster.local"

            - name: CLICKHOUSE_PORT
              value: "8123"

            - name: CLICKHOUSE_USER
              value: "default"

            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-clickhouse-secret
                  key: password

            - name: CLICKHOUSE_DATABASE
              value: "analytics"
          # envFrom:
          #   - configMapRef:
          #       name: platform-config

          #   - secretRef:
          #       name: platform-secrets

          readinessProbe:
            httpGet:
              path: {{ .Values.eventService.readinessPath }}
              port: http

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: {{ .Values.eventService.livenessPath }}
              port: http

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
{{ toYaml .Values.eventService.resources | indent 12 }}

---

apiVersion: v1
kind: Service

metadata:
  name: event-service
  labels:
    app: event-service

spec:
  type: ClusterIP

  selector:
    app: event-service

  ports:
    - name: http
      port: {{ .Values.eventService.port }}
      targetPort: http
      protocol: TCP

{{- end }}