{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: new-event-ingress

  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /api/events
            pathType: Prefix

            backend:
              service:
                name: event-service

                port:
                  number: {{ .Values.eventService.port }}

          - path: /api/programs
            pathType: Prefix

            backend:
              service:
                name: program-service

                port:
                  number: {{ .Values.programService.port }}

          - path: /api/registrations
            pathType: Prefix

            backend:
              service:
                name: registration-service

                port:
                  number: {{ .Values.registrationService.port }}

          - path: /api/analytics
            pathType: Prefix

            backend:
              service:
                name: analytics-service

                port:
                  number: {{ .Values.analyticsService.port }}

          - path: /
            pathType: Prefix

            backend:
              service:
                name: event-frontend

                port:
                  number: {{ .Values.frontend.port }}


{{- end }}