apiVersion: v1
kind: Secret

metadata:
  name: platform-secrets
  labels:
    app.kubernetes.io/name: new-event-platform

type: Opaque

stringData:
  DATABASE_URL: {{ required "database.url must be provided" .Values.database.url | quote }}

  LAMBDA_FUNCTION_URL: {{ required "lambda.functionUrl must be provided" .Values.lambda.functionUrl | quote }}

  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}