name: deploy-dev

on:
  push:
    branches: [main]
    paths:
      - "services/**"
      - "helm/new-event-platform/**"
      - ".github/workflows/four-services-helm-blue-green.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE || 'default' }}
  ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  HELM_RELEASE: new-event-platform
  HELM_CHART: ./helm/new-event-platform

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Verify AWS connection
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Test ECR access
        run: |
          aws ecr describe-repositories \
          --region "$AWS_REGION"

      - name: Test EKS connection
        run: |
          aws eks update-kubeconfig \
          --region "$AWS_REGION" \
          --name "$EKS_CLUSTER_NAME"

          kubectl get nodes
          kubectl get pods -n "$K8S_NAMESPACE"
